### ISSUE TITLE
Tracking: Kord Contexts

### ISSUE THREAD

**Issue by gdude2002** [Kotlin-Discord/kord-extensions#72]
This is a tracking issue that contains a rough overview of what needs to be done to adapt KordEx to Kord's new `contexts` branch. This is going to require a rewrite of several systems, but it's ultimately for the best for everyone. There's a bunch of work to do in this list, but we've got this!

- [x] Rewrite the components system to use typed events and a centralized event system 
    - [x] #63
- [x] Disable message commands by default, and rename them to chat commands
- [x] Split command and event functions out of the `Extension` class into extension functions
- [x] Split out slash commands from message and user commands, and use typed events for them
    - [x] Redo the slash command flow, with different builders for specific slash command response types and a unified API
- [x] Build an API that allows for post-startup registration and deregistration of interaction commands
- [x] ~~Figure out the new ack types for slash commands and~~ try to adapt the paginator to ephemeral flows
- [x] Kotlin 1.5.30
- [x] Remove anything that was deprecated in previous versions

Other things that I'd like to get done before we make a release:

- [x] Refactor the Sentry integration to use a `SentryContext` class (which we'll have to provide)
- [x] Add validation for command arguments classes that have multiple arguments with the same name (especially since this already breaks all types of commands)
- [x] Switch to builder-only syntax for all checks
- [x] Add event objects to callback-based checks, making them generic
- [x] Make grouped chat commands peek instead of consume a token to check for the command name
- [x] #73
- [x] Set up automatic signing for KordEx artefacts
- [x] Review debug-level logging calls, and move some to trace level as appropriate

**Comment by gdude2002** [comment]
Notes from Discord:

- [x] Add `unsafe` module with less strictly handled actionable interaction types
- [x] ComponentContainer doesn't clear components in message builders

**Comment by gdude2002** [comment]
Believe it or not, this issue has been completed. I'll leave it open for a bit so people can try things out and port their bots over - I guess the next thing I'll have to do is documentation...

**Comment by gdude2002** [comment]
I'm largely happy with how this has worked out. Things are mostly done here now, and I think we're OK to move ahead and get the docs ready and do a release.
